// <auto-generated />
using System;
using BrowserHistory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrowserHistory.Infrastructure.Migrations
{
    [DbContext(typeof(BrowserHistoryDbContext))]
    [Migration("20250711180639_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BrowserHistory.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("DeviceName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastSeen");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("RegisteredAt");

                    b.HasKey("Id");

                    b.HasIndex("DeviceName")
                        .IsUnique()
                        .HasDatabaseName("IX_Devices_DeviceName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Devices_IsActive");

                    b.HasIndex("LastSeen")
                        .HasDatabaseName("IX_Devices_LastSeen");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("BrowserHistory.Domain.Entities.HistoryNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("FaviconUrl");

                    b.Property<bool>("IsBookmarked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsBookmarked");

                    b.Property<DateTime>("LastVisitedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastVisitedAt");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("Url");

                    b.Property<int>("VisitCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VisitCount");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("VisitedAt");

                    b.HasKey("Id");

                    b.HasIndex("IsBookmarked")
                        .HasDatabaseName("IX_HistoryNodes_IsBookmarked");

                    b.HasIndex("LastVisitedAt")
                        .HasDatabaseName("IX_HistoryNodes_LastVisitedAt");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_HistoryNodes_Title");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("IX_HistoryNodes_Url");

                    b.HasIndex("Title", "Url")
                        .HasDatabaseName("IX_HistoryNodes_Search");

                    b.ToTable("HistoryNodes", (string)null);
                });

            modelBuilder.Entity("BrowserHistory.Domain.Entities.SyncEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeviceId");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EventType");

                    b.Property<string>("Metadata")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("IX_SyncEvents_DeviceId");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_SyncEvents_EventType");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_SyncEvents_Timestamp");

                    b.HasIndex("DeviceId", "Timestamp")
                        .HasDatabaseName("IX_SyncEvents_DeviceId_Timestamp");

                    b.ToTable("SyncEvents", (string)null);
                });

            modelBuilder.Entity("BrowserHistory.Domain.Entities.SyncEvent", b =>
                {
                    b.HasOne("BrowserHistory.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
