// <auto-generated />
using System;
using BrowserHistory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrowserHistory.Infrastructure.Migrations
{
    [DbContext(typeof(BrowserHistoryDbContext))]
    [Migration("20260922214323_FixSyncEventEntityIdAndSchema")]
    partial class FixSyncEventEntityIdAndSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BrowserHistory.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("DeviceName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastSeen");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("RegisteredAt");

                    b.HasKey("Id");

                    b.HasIndex("DeviceName")
                        .IsUnique()
                        .HasDatabaseName("IX_Devices_DeviceName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Devices_IsActive");

                    b.HasIndex("LastSeen")
                        .HasDatabaseName("IX_Devices_LastSeen");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("BrowserHistory.Domain.Entities.HistoryNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("FaviconUrl");

                    b.Property<bool>("IsBookmarked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsBookmarked");

                    b.Property<DateTime>("LastVisitedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastVisitedAt");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("Url");

                    b.Property<int>("VisitCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VisitCount");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("VisitedAt");

                    b.HasKey("Id");

                    b.HasIndex("IsBookmarked")
                        .HasDatabaseName("IX_HistoryNodes_IsBookmarked");

                    b.HasIndex("LastVisitedAt")
                        .HasDatabaseName("IX_HistoryNodes_LastVisitedAt");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_HistoryNodes_Title");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("IX_HistoryNodes_Url");

                    b.HasIndex("Title", "Url")
                        .HasDatabaseName("IX_HistoryNodes_Search");

                    b.ToTable("HistoryNodes", (string)null);
                });

            modelBuilder.Entity("BrowserHistory.Domain.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("Content");

                    b.Property<long>("ContentLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ContentLength");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ContentType");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("FaviconUrl");

                    b.Property<string>("Keywords")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Keywords");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("Language");

                    b.Property<DateTime>("LastIndexedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastIndexedAt");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StatusCode");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.HasIndex("ContentLength")
                        .HasDatabaseName("IX_Pages_ContentLength");

                    b.HasIndex("Language")
                        .HasDatabaseName("IX_Pages_Language");

                    b.HasIndex("LastIndexedAt")
                        .HasDatabaseName("IX_Pages_LastIndexedAt");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Pages_Title");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("IX_Pages_Url");

                    b.ToTable("Pages", (string)null);
                });

            modelBuilder.Entity("BrowserHistory.Domain.Entities.SyncEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Checksum");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Data");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeviceId");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("EntityId");

                    b.Property<int>("EntityType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EntityType");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EventType");

                    b.Property<string>("Metadata")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Checksum")
                        .HasDatabaseName("IX_SyncEvents_Checksum");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("IX_SyncEvents_DeviceId");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("IX_SyncEvents_EntityId");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("IX_SyncEvents_EntityType");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_SyncEvents_EventType");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_SyncEvents_Timestamp");

                    b.HasIndex("DeviceId", "Timestamp")
                        .HasDatabaseName("IX_SyncEvents_DeviceId_Timestamp");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_SyncEvents_EntityType_EntityId");

                    b.ToTable("SyncEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
