// <auto-generated />
using System;
using BrowserHistory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrowserHistory.Infrastructure.Migrations
{
    [DbContext(typeof(BrowserHistoryDbContext))]
    [Migration("20260923122111_RemoveUnusedHistoryAndPageTables")]
    partial class RemoveUnusedHistoryAndPageTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BrowserHistory.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("DeviceName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastSeen");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("RegisteredAt");

                    b.HasKey("Id");

                    b.HasIndex("DeviceName")
                        .IsUnique()
                        .HasDatabaseName("IX_Devices_DeviceName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Devices_IsActive");

                    b.HasIndex("LastSeen")
                        .HasDatabaseName("IX_Devices_LastSeen");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("BrowserHistory.Domain.Entities.SyncEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Checksum");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Data");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeviceId");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("EntityId");

                    b.Property<int>("EntityType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EntityType");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EventType");

                    b.Property<string>("Metadata")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Metadata");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Checksum")
                        .HasDatabaseName("IX_SyncEvents_Checksum");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("IX_SyncEvents_DeviceId");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("IX_SyncEvents_EntityId");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("IX_SyncEvents_EntityType");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_SyncEvents_EventType");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_SyncEvents_Timestamp");

                    b.HasIndex("DeviceId", "Timestamp")
                        .HasDatabaseName("IX_SyncEvents_DeviceId_Timestamp");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_SyncEvents_EntityType_EntityId");

                    b.ToTable("SyncEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
